package fxPankki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPankki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.16 22:05:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AsiakasTest {


  // Generated by ComTest BEGIN
  /** testGetNimi32 */
  @Test
  public void testGetNimi32() {    // Asiakas: 32
    Asiakas asiakas = new Asiakas(); 
    asiakas.vastaaErik(); 
    { String _l_=asiakas.getNimi(),_r_="Tino Harjumäki.*"; if ( !_l_.matches(_r_) ) fail("From: Asiakas line: 35" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone169 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone169() throws CloneNotSupportedException {    // Asiakas: 169
    Asiakas asiakas = new Asiakas(); 
    asiakas.parse("3|Tino Harjumäki|040506-321H|jokutie|00000|Jyväskylä|123454321|tiantaha@jyu.fi"); 
    Asiakas kopio = asiakas.clone(); 
    assertEquals("From: Asiakas line: 174", asiakas.toString(), kopio.toString()); 
    asiakas.parse("4|Tino Tupu|040506-321H|jokutie|00000|Jyväskylä|123454321|tiantaha@jyu.fi"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString211 */
  @Test
  public void testToString211() {    // Asiakas: 211
    Asiakas asiakas = new Asiakas(); 
    asiakas.parse("3|Tino Harjumäki|040506-321H|jokutie|00000|Jyväskylä|123454321|tiantaha@jyu.fi"); 
    assertEquals("From: Asiakas line: 214", 3, asiakas.getTunnusNro()); 
    assertEquals("From: Asiakas line: 215", true, asiakas.toString().startsWith("3|Tino Harjumäki|040506-321H|jokutie|00000|Jyväskylä|123454321|tiantaha@jyu.fi")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse236 */
  @Test
  public void testParse236() {    // Asiakas: 236
    Asiakas asiakas = new Asiakas(); 
    asiakas.parse("3|Tino Harjumäki|040506-321H|jokutie|00000|Jyväskylä|123454321|tiantaha@jyu.fi"); 
    assertEquals("From: Asiakas line: 239", 3, asiakas.getTunnusNro()); 
    assertEquals("From: Asiakas line: 240", true, asiakas.toString().startsWith("3|Tino Harjumäki|040506-321H|jokutie|00000|Jyväskylä|123454321|tiantaha@jyu.fi")); 
    asiakas.rekisteroi(); 
    int n = asiakas.getTunnusNro(); 
    asiakas.parse(""+(n+20)); 
    asiakas.rekisteroi(); 
    assertEquals("From: Asiakas line: 246", n+21, asiakas.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta375 */
  @Test
  public void testAseta375() {    // Asiakas: 375
    Asiakas asiakas = new Asiakas(); 
    assertEquals("From: Asiakas line: 377", null, asiakas.aseta(1,"Tino Harjumäki")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi421 */
  @Test
  public void testRekisteroi421() {    // Asiakas: 421
    Asiakas asiakas1 = new Asiakas(); 
    assertEquals("From: Asiakas line: 423", 0, asiakas1.getTunnusNro()); 
    asiakas1.rekisteroi(); 
    Asiakas asiakas2 = new Asiakas(); 
    asiakas2.rekisteroi(); 
    int n1 = asiakas1.getTunnusNro(); 
    int n2 = asiakas2.getTunnusNro(); 
    assertEquals("From: Asiakas line: 429", n2-1, n1); 
  } // Generated by ComTest END
}