package fxPankki.test;
// Generated by ComTest BEGIN
import KorttiRekisteri.SailoException;
import java.util.*;
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import fxPankki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.16 22:59:11 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PankkiTest {


  // Generated by ComTest BEGIN  // Pankki: 21
   private Pankki pankki; 
   private Asiakas aku1; 
   private Asiakas aku2; 
   private int jid1; 
   private int jid2; 
   private Debit pitsi21; 
   private Credit pitsi11; 
   private Yhdistelmä pitsi22; 
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista48 */
  @Test
  public void testPoista48() {    // Pankki: 48
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaDebit68 */
  @Test
  public void testPoistaDebit68() {    // Pankki: 68
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaCredit80 */
  @Test
  public void testPoistaCredit80() {    // Pankki: 80
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa105 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa105() throws SailoException {    // Pankki: 105
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa155 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa155() throws SailoException {    // Pankki: 155
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaDebit192 
 * @throws SailoException jos laiton */
  @Test
  public void testAnnaDebit192() throws SailoException {    // Pankki: 192

  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaCredit218 
  * @throws SailoException jos laiton */
  @Test
  public void testAnnaCredit218() throws SailoException {    // Pankki: 218

  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta279 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta279() throws SailoException {    // Pankki: 279
    String hakemisto = "testipankki"; 
    File dir = new File(hakemisto); 
    File fAsiakkaat  = new File(hakemisto+"/asiakkaat.dat"); 
    File fKortit = new File(hakemisto+"/kortit.dat"); 
    dir.mkdir(); 
    fAsiakkaat.delete(); 
    fKortit.delete(); 
    pankki = new Pankki();  // tiedostoja ei ole, tulee poikkeus 
    try {
    pankki.lueTiedostosta(hakemisto); 
    } catch(SailoException _e_){ _e_.getMessage(); }
    pankki.setTiedosto(hakemisto);  // nimi annettava koska uusi poisti sen
    pankki.tallenna(); 
    pankki = new Pankki(); 
    pankki.lueTiedostosta(hakemisto); 
    Collection<Asiakas> kaikki = pankki.etsi("", -1); 
    Iterator<Asiakas> it = kaikki.iterator(); 
    assertEquals("From: Pankki line: 304", false, it.hasNext()); 
    pankki.lisaa(aku2); 
    pankki.lisaaDebit(pitsi21); 
    assertEquals("From: Pankki line: 314", false, fAsiakkaat.delete()); 
    assertEquals("From: Pankki line: 315", false, fKortit.delete()); 
    File fbak = new File(hakemisto+"/asiakkaat.bak"); 
    File fcbak = new File(hakemisto+"/kortit.bak"); 
    assertEquals("From: Pankki line: 318", false, fbak.delete()); 
    assertEquals("From: Pankki line: 319", false, fcbak.delete()); 
    assertEquals("From: Pankki line: 320", false, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsi404 */
  @Test
  public void testEtsi404() {    // Pankki: 404
    Asiakas asiakas3 = new Asiakas(); asiakas3.rekisteroi(); 
    asiakas3.aseta(1,"Susi Sepe"); 
  } // Generated by ComTest END
}